// Generated by CoffeeScript 2.7.0
(function() {
  var Validation, words_testcases;

  Validation = require("../validation");

  words_testcases = [
    {
      description: 'One unsupported custom emoji and one unicode emoji',
      words: ['<:carl:762777713949540402>',
    'Carl,',
    '🧨',
    'Jake'],
      pairs: [
        {
          name: 'Carl',
          emoji: '<:carl:762777713949540402>'
        },
        {
          name: 'Jake',
          emoji: '🧨'
        }
      ]
    },
    {
      // tb! roles 🍣 Sushi, ⚾ Baseball
      description: 'Two unicode emojis and some whitespace.',
      words: [' 🍣   ',
    ' Sushi,  ',
    '  ⚾   ',
    ' Baseball '],
      pairs: [
        {
          name: 'Sushi',
          emoji: '🍣'
        },
        {
          name: 'Baseball',
          emoji: '⚾'
        }
      ]
    }
  ];

  // The 'test' function doesn't seem to work in an inner loop.  Oh well.
  test('All word testcases.', () => {
    var i, j, p, pairs, ref, ref1, t, testcase;
    for (t = i = 0, ref = words_testcases.length - 1; (0 <= ref ? i <= ref : i >= ref); t = 0 <= ref ? ++i : --i) {
      testcase = words_testcases[t];
      pairs = Validation.validate_pairs(testcase.words);
      expect(pairs.length).toBe(testcase.pairs.length);
      for (p = j = 0, ref1 = pairs.length - 1; (0 <= ref1 ? j <= ref1 : j >= ref1); p = 0 <= ref1 ? ++j : --j) {
        expect(pairs[p].name).toBe(testcase.pairs[p].name);
        expect(pairs[p].emoji).toBe(testcase.pairs[p].emoji);
      }
    }
  });

}).call(this);
