// Generated by CoffeeScript 2.7.0
(function() {
  var SlashCommandBuilder;

  ({SlashCommandBuilder} = require('@discordjs/builders'));

  module.exports = {
    data: new SlashCommandBuilder().setName('ping_three').setDescription('Replies with Pong!'),
    execute: async(interaction) => {
      console.log('Execute triggered...');
      return (await interaction.reply('Pong!'));
    }
  };

}).call(this);
